// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/ai/generate_quiz_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pg_manager/domain/entities/quiz.dart' as _i2;
import 'package:pg_manager/domain/services/ai_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeQuiz_0 extends _i1.SmartFake implements _i2.Quiz {
  _FakeQuiz_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i3.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> chat({
    required String? message,
    List<_i3.AiChatTurn>? conversationHistory = const [],
    String? systemInstruction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chat, [], {
              #message: message,
              #conversationHistory: conversationHistory,
              #systemInstruction: systemInstruction,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#chat, [], {
                  #message: message,
                  #conversationHistory: conversationHistory,
                  #systemInstruction: systemInstruction,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> chatWithImage({
    required String? message,
    required _i6.Uint8List? imageBytes,
    required String? mimeType,
    List<_i3.AiChatTurn>? conversationHistory = const [],
    String? systemInstruction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chatWithImage, [], {
              #message: message,
              #imageBytes: imageBytes,
              #mimeType: mimeType,
              #conversationHistory: conversationHistory,
              #systemInstruction: systemInstruction,
            }),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#chatWithImage, [], {
                  #message: message,
                  #imageBytes: imageBytes,
                  #mimeType: mimeType,
                  #conversationHistory: conversationHistory,
                  #systemInstruction: systemInstruction,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.Quiz> generateQuiz({
    required String? text,
    int? questionCount = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateQuiz, [], {
              #text: text,
              #questionCount: questionCount,
            }),
            returnValue: _i4.Future<_i2.Quiz>.value(
              _FakeQuiz_0(
                this,
                Invocation.method(#generateQuiz, [], {
                  #text: text,
                  #questionCount: questionCount,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Quiz>);

  @override
  _i4.Future<String> summarize({required String? text}) =>
      (super.noSuchMethod(
            Invocation.method(#summarize, [], {#text: text}),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#summarize, [], {#text: text}),
              ),
            ),
          )
          as _i4.Future<String>);
}
