// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/current_affairs/current_affairs_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/current_affair.dart' as _i6;
import 'package:pg_manager/domain/repositories/current_affairs_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CurrentAffairsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrentAffairsRepository extends _i1.Mock
    implements _i3.CurrentAffairsRepository {
  MockCurrentAffairsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>> create({
    required String? title,
    required String? summary,
    required String? content,
    required _i6.CurrentAffairsCategory? category,
    String? source,
    String? imageUrl,
    required String? createdBy,
    bool? sendNotification = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #title: title,
              #summary: summary,
              #content: content,
              #category: category,
              #source: source,
              #imageUrl: imageUrl,
              #createdBy: createdBy,
              #sendNotification: sendNotification,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CurrentAffair>(
                    this,
                    Invocation.method(#create, [], {
                      #title: title,
                      #summary: summary,
                      #content: content,
                      #category: category,
                      #source: source,
                      #imageUrl: imageUrl,
                      #createdBy: createdBy,
                      #sendNotification: sendNotification,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i3.PaginatedCurrentAffairs>> getAll({
    _i6.CurrentAffairsCategory? category,
    int? limit = 10,
    String? startAfterId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #category: category,
              #limit: limit,
              #startAfterId: startAfterId,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i3.PaginatedCurrentAffairs>
                >.value(
                  _FakeEither_0<_i5.Failure, _i3.PaginatedCurrentAffairs>(
                    this,
                    Invocation.method(#getAll, [], {
                      #category: category,
                      #limit: limit,
                      #startAfterId: startAfterId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i3.PaginatedCurrentAffairs>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>> getById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>>.value(
                  _FakeEither_0<_i5.Failure, _i6.CurrentAffair>(
                    this,
                    Invocation.method(#getById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CurrentAffair>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> toggleBookmark({
    required String? currentAffairId,
    required String? userId,
    required bool? isBookmarked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [], {
              #currentAffairId: currentAffairId,
              #userId: userId,
              #isBookmarked: isBookmarked,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#toggleBookmark, [], {
                  #currentAffairId: currentAffairId,
                  #userId: userId,
                  #isBookmarked: isBookmarked,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Set<String>>> getBookmarkedIds(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarkedIds, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, Set<String>>>.value(
              _FakeEither_0<_i5.Failure, Set<String>>(
                this,
                Invocation.method(#getBookmarkedIds, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Set<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> recordView({
    required String? currentAffairId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordView, [], {
              #currentAffairId: currentAffairId,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#recordView, [], {
                  #currentAffairId: currentAffairId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> toggleLike({
    required String? currentAffairId,
    required String? userId,
    required bool? isLiked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleLike, [], {
              #currentAffairId: currentAffairId,
              #userId: userId,
              #isLiked: isLiked,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#toggleLike, [], {
                  #currentAffairId: currentAffairId,
                  #userId: userId,
                  #isLiked: isLiked,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Set<String>>> getLikedIds(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLikedIds, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, Set<String>>>.value(
              _FakeEither_0<_i5.Failure, Set<String>>(
                this,
                Invocation.method(#getLikedIds, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Set<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#delete, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
