// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/referral/create_referral_code_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/coupon.dart' as _i10;
import 'package:pg_manager/domain/entities/owner_trial.dart' as _i9;
import 'package:pg_manager/domain/entities/referral.dart' as _i6;
import 'package:pg_manager/domain/entities/subscription.dart' as _i8;
import 'package:pg_manager/domain/repositories/referral_repository.dart' as _i3;
import 'package:pg_manager/domain/repositories/subscription_repository.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReferralRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReferralRepository extends _i1.Mock
    implements _i3.ReferralRepository {
  MockReferralRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>> createReferral(
    _i6.Referral? referral,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createReferral, [referral]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Referral>(
                    this,
                    Invocation.method(#createReferral, [referral]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>> getReferralByOwnerId(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReferralByOwnerId, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Referral?>(
                    this,
                    Invocation.method(#getReferralByOwnerId, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>> getReferralByCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReferralByCode, [code]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Referral?>(
                    this,
                    Invocation.method(#getReferralByCode, [code]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Referral?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>> updateReferral(
    _i6.Referral? referral,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateReferral, [referral]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Referral>(
                    this,
                    Invocation.method(#updateReferral, [referral]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Referral>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption>> createRedemption(
    _i6.ReferralRedemption? redemption,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createRedemption, [redemption]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ReferralRedemption>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ReferralRedemption>(
                    this,
                    Invocation.method(#createRedemption, [redemption]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption>> updateRedemption(
    _i6.ReferralRedemption? redemption,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateRedemption, [redemption]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ReferralRedemption>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ReferralRedemption>(
                    this,
                    Invocation.method(#updateRedemption, [redemption]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>>
  getRedemptionsByReferrer(String? referrerId) =>
      (super.noSuchMethod(
            Invocation.method(#getRedemptionsByReferrer, [referrerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ReferralRedemption>>(
                    this,
                    Invocation.method(#getRedemptionsByReferrer, [referrerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption?>>
  getRedemptionByReferee(String? refereeId) =>
      (super.noSuchMethod(
            Invocation.method(#getRedemptionByReferee, [refereeId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ReferralRedemption?>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ReferralRedemption?>(
                    this,
                    Invocation.method(#getRedemptionByReferee, [refereeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralRedemption?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>>
  getUnclaimedRewards(String? referrerId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnclaimedRewards, [referrerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ReferralRedemption>>(
                    this,
                    Invocation.method(#getUnclaimedRewards, [referrerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ReferralRedemption>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>> getOrCreateWallet(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateWallet, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ReferralWallet>(
                    this,
                    Invocation.method(#getOrCreateWallet, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>> updateWallet(
    _i6.ReferralWallet? wallet,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateWallet, [wallet]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ReferralWallet>(
                    this,
                    Invocation.method(#updateWallet, [wallet]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ReferralWallet>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WithdrawalRequest>>
  createWithdrawalRequest(_i6.WithdrawalRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createWithdrawalRequest, [request]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.WithdrawalRequest>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.WithdrawalRequest>(
                    this,
                    Invocation.method(#createWithdrawalRequest, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.WithdrawalRequest>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>>
  getWithdrawalRequests(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getWithdrawalRequests, [ownerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.WithdrawalRequest>>(
                    this,
                    Invocation.method(#getWithdrawalRequests, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>>
  getAllPendingWithdrawals() =>
      (super.noSuchMethod(
            Invocation.method(#getAllPendingWithdrawals, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.WithdrawalRequest>>(
                    this,
                    Invocation.method(#getAllPendingWithdrawals, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.WithdrawalRequest>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.WithdrawalRequest>>
  updateWithdrawalRequest(_i6.WithdrawalRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateWithdrawalRequest, [request]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.WithdrawalRequest>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.WithdrawalRequest>(
                    this,
                    Invocation.method(#updateWithdrawalRequest, [request]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.WithdrawalRequest>>);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i7.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>> createSubscription(
    _i8.Subscription? subscription,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [subscription]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i8.Subscription>(
                    this,
                    Invocation.method(#createSubscription, [subscription]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>> updateSubscription(
    _i8.Subscription? subscription,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscription, [subscription]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i8.Subscription>(
                    this,
                    Invocation.method(#updateSubscription, [subscription]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>> getActiveSubscription(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSubscription, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>>.value(
                  _FakeEither_0<_i5.Failure, _i8.Subscription?>(
                    this,
                    Invocation.method(#getActiveSubscription, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>> getSubscriptionById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i8.Subscription>(
                    this,
                    Invocation.method(#getSubscriptionById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>
  getSubscriptionHistory(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionHistory, [ownerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Subscription>>(
                    this,
                    Invocation.method(#getSubscriptionHistory, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>
  getPendingVerificationSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingVerificationSubscriptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Subscription>>(
                    this,
                    Invocation.method(#getPendingVerificationSubscriptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>>
  getLatestPendingSubscription(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestPendingSubscription, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>>.value(
                  _FakeEither_0<_i5.Failure, _i8.Subscription?>(
                    this,
                    Invocation.method(#getLatestPendingSubscription, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Subscription?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>
  getAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubscriptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Subscription>>(
                    this,
                    Invocation.method(#getAllSubscriptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSubscription(
    String? subscriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubscription, [subscriptionId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteSubscription, [subscriptionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>> getOrCreateTrial(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateTrial, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>>.value(
                  _FakeEither_0<_i5.Failure, _i9.OwnerTrial>(
                    this,
                    Invocation.method(#getOrCreateTrial, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial?>> getTrial(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTrial, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial?>>.value(
                  _FakeEither_0<_i5.Failure, _i9.OwnerTrial?>(
                    this,
                    Invocation.method(#getTrial, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>> updateTrial(
    _i9.OwnerTrial? trial,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrial, [trial]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>>.value(
                  _FakeEither_0<_i5.Failure, _i9.OwnerTrial>(
                    this,
                    Invocation.method(#updateTrial, [trial]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.OwnerTrial>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon?>> getCouponByCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCouponByCode, [code]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon?>>.value(
                  _FakeEither_0<_i5.Failure, _i10.Coupon?>(
                    this,
                    Invocation.method(#getCouponByCode, [code]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>> createCoupon(
    _i10.Coupon? coupon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCoupon, [coupon]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>>.value(
              _FakeEither_0<_i5.Failure, _i10.Coupon>(
                this,
                Invocation.method(#createCoupon, [coupon]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>> updateCoupon(
    _i10.Coupon? coupon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoupon, [coupon]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>>.value(
              _FakeEither_0<_i5.Failure, _i10.Coupon>(
                this,
                Invocation.method(#updateCoupon, [coupon]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.Coupon>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i10.Coupon>>> getAllCoupons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCoupons, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i10.Coupon>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i10.Coupon>>(
                    this,
                    Invocation.method(#getAllCoupons, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i10.Coupon>>>);
}
