// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/presentation/student/student_home_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:dartz/dartz.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/core.dart' as _i11;
import 'package:pg_manager/domain/entities/membership.dart' as _i15;
import 'package:pg_manager/domain/entities/presence.dart' as _i13;
import 'package:pg_manager/domain/entities/slot.dart' as _i18;
import 'package:pg_manager/domain/entities/student_document.dart' as _i21;
import 'package:pg_manager/domain/entities/user.dart' as _i17;
import 'package:pg_manager/domain/repositories/auth_repository.dart' as _i16;
import 'package:pg_manager/domain/repositories/invoice_repository.dart' as _i7;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i3;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i2;
import 'package:pg_manager/domain/repositories/presence_repository.dart' as _i6;
import 'package:pg_manager/domain/repositories/slot_repository.dart' as _i4;
import 'package:pg_manager/domain/repositories/student_document_repository.dart'
    as _i8;
import 'package:pg_manager/domain/repositories/user_repository.dart' as _i19;
import 'package:pg_manager/domain/usecases/get_student_documents.dart' as _i20;
import 'package:pg_manager/domain/usecases/get_student_memberships.dart' as _i9;
import 'package:pg_manager/domain/usecases/sync_memberships_on_login.dart'
    as _i14;
import 'package:pg_manager/domain/usecases/validate_daily_presence.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMembershipRepository_0 extends _i1.SmartFake
    implements _i2.MembershipRepository {
  _FakeMembershipRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLibraryRepository_1 extends _i1.SmartFake
    implements _i3.LibraryRepository {
  _FakeLibraryRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSlotRepository_2 extends _i1.SmartFake
    implements _i4.SlotRepository {
  _FakeSlotRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_3<L, R> extends _i1.SmartFake implements _i5.Either<L, R> {
  _FakeEither_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePresenceRepository_4 extends _i1.SmartFake
    implements _i6.PresenceRepository {
  _FakePresenceRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvoiceRepository_5 extends _i1.SmartFake
    implements _i7.InvoiceRepository {
  _FakeInvoiceRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStudentDocumentRepository_6 extends _i1.SmartFake
    implements _i8.StudentDocumentRepository {
  _FakeStudentDocumentRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetStudentMemberships].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStudentMemberships extends _i1.Mock
    implements _i9.GetStudentMemberships {
  MockGetStudentMemberships() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i3.LibraryRepository get libraryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#libraryRepository),
            returnValue: _FakeLibraryRepository_1(
              this,
              Invocation.getter(#libraryRepository),
            ),
          )
          as _i3.LibraryRepository);

  @override
  _i4.SlotRepository get slotRepository =>
      (super.noSuchMethod(
            Invocation.getter(#slotRepository),
            returnValue: _FakeSlotRepository_2(
              this,
              Invocation.getter(#slotRepository),
            ),
          )
          as _i4.SlotRepository);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i9.StudentMembershipInfo>>> call(
    _i9.GetStudentMembershipsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i9.StudentMembershipInfo>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i9.StudentMembershipInfo>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i10.Future<
            _i5.Either<_i11.Failure, List<_i9.StudentMembershipInfo>>
          >);
}

/// A class which mocks [ValidateDailyPresence].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateDailyPresence extends _i1.Mock
    implements _i12.ValidateDailyPresence {
  MockValidateDailyPresence() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.PresenceRepository get presenceRepository =>
      (super.noSuchMethod(
            Invocation.getter(#presenceRepository),
            returnValue: _FakePresenceRepository_4(
              this,
              Invocation.getter(#presenceRepository),
            ),
          )
          as _i6.PresenceRepository);

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i13.Presence>> call(
    _i12.ValidateDailyPresenceParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i13.Presence>>.value(
                  _FakeEither_3<_i11.Failure, _i13.Presence>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i13.Presence>>);
}

/// A class which mocks [SyncMembershipsOnLogin].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncMembershipsOnLogin extends _i1.Mock
    implements _i14.SyncMembershipsOnLogin {
  MockSyncMembershipsOnLogin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i7.InvoiceRepository get invoiceRepository =>
      (super.noSuchMethod(
            Invocation.getter(#invoiceRepository),
            returnValue: _FakeInvoiceRepository_5(
              this,
              Invocation.getter(#invoiceRepository),
            ),
          )
          as _i7.InvoiceRepository);

  @override
  _i8.StudentDocumentRepository get documentRepository =>
      (super.noSuchMethod(
            Invocation.getter(#documentRepository),
            returnValue: _FakeStudentDocumentRepository_6(
              this,
              Invocation.getter(#documentRepository),
            ),
          )
          as _i8.StudentDocumentRepository);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>> call(
    _i14.SyncMembershipsOnLoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i16.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Stream<_i17.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i10.Stream<_i17.User?>.empty(),
          )
          as _i10.Stream<_i17.User?>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, String>> sendOtp(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [phoneNumber]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, String>>.value(
              _FakeEither_3<_i11.Failure, String>(
                this,
                Invocation.method(#sendOtp, [phoneNumber]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, String>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User>> verifyOtp({
    required String? verificationId,
    required String? otp,
    required String? deviceId,
    required _i17.UserRole? role,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #verificationId: verificationId,
              #otp: otp,
              #deviceId: deviceId,
              #role: role,
              #name: name,
            }),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, _i17.User>>.value(
              _FakeEither_3<_i11.Failure, _i17.User>(
                this,
                Invocation.method(#verifyOtp, [], {
                  #verificationId: verificationId,
                  #otp: otp,
                  #deviceId: deviceId,
                  #role: role,
                  #name: name,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>.value(
                  _FakeEither_3<_i11.Failure, _i17.User?>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User?>> getUserByDeviceId(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByDeviceId, [deviceId]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>.value(
                  _FakeEither_3<_i11.Failure, _i17.User?>(
                    this,
                    Invocation.method(#getUserByDeviceId, [deviceId]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User?>> getUserByPhone(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phoneNumber]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>.value(
                  _FakeEither_3<_i11.Failure, _i17.User?>(
                    this,
                    Invocation.method(#getUserByPhone, [phoneNumber]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, String>> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, String>>.value(
              _FakeEither_3<_i11.Failure, String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, String>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User>> updateUserProfile({
    required String? userId,
    required String? name,
    String? avatarUrl,
    String? examPreparingFor,
    bool? isAccessCardIssued,
    String? address,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #userId: userId,
              #name: name,
              #avatarUrl: avatarUrl,
              #examPreparingFor: examPreparingFor,
              #isAccessCardIssued: isAccessCardIssued,
              #address: address,
              #gender: gender,
            }),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, _i17.User>>.value(
              _FakeEither_3<_i11.Failure, _i17.User>(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #userId: userId,
                  #name: name,
                  #avatarUrl: avatarUrl,
                  #examPreparingFor: examPreparingFor,
                  #isAccessCardIssued: isAccessCardIssued,
                  #address: address,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User>>);
}

/// A class which mocks [MembershipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembershipRepository extends _i1.Mock
    implements _i2.MembershipRepository {
  MockMembershipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>> createMembership(
    _i15.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMembership, [membership]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#createMembership, [membership]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>> getMembershipById(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipById, [membershipId]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#getMembershipById, [membershipId]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>
  getActiveMembershipByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>
  getActiveMembershipByUserLibraryAndSlot({
    required String? userId,
    required String? libraryId,
    required _i18.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserLibraryAndSlot, [], {
              #userId: userId,
              #libraryId: libraryId,
              #slot: slot,
            }),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserLibraryAndSlot,
                      [],
                      {#userId: userId, #libraryId: libraryId, #slot: slot},
                    ),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getActiveMembershipsByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveMembershipsByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getMembershipsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByUserId, [userId]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByUserId, [userId]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getMembershipsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByLibraryId, [libraryId]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getActiveMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsForLibrary, [libraryId]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getActiveMembershipsForLibrary, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getActiveAndReservedMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAndReservedMembershipsForLibrary, [
              libraryId,
            ]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveAndReservedMembershipsForLibrary,
                      [libraryId],
                    ),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getExpiredMembershipsWithSeatsForLibrary({
    required String? libraryId,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMembershipsWithSeatsForLibrary, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
            }),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(
                      #getExpiredMembershipsWithSeatsForLibrary,
                      [],
                      {#libraryId: libraryId, #currentDate: currentDate},
                    ),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, bool>> isSeatSlotOccupied({
    required String? libraryId,
    required String? seatId,
    required _i18.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSeatSlotOccupied, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, bool>>.value(
              _FakeEither_3<_i11.Failure, bool>(
                this,
                Invocation.method(#isSeatSlotOccupied, [], {
                  #libraryId: libraryId,
                  #seatId: seatId,
                  #slot: slot,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, bool>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>
  getMembershipBySeatAndSlot({
    required String? libraryId,
    required String? seatId,
    required _i18.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipBySeatAndSlot, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership?>(
                    this,
                    Invocation.method(#getMembershipBySeatAndSlot, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                      #slot: slot,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getMembershipsBySeatId({
    required String? libraryId,
    required String? seatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsBySeatId, [], {
              #libraryId: libraryId,
              #seatId: seatId,
            }),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getMembershipsBySeatId, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>> updateMembership(
    _i15.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMembership, [membership]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>.value(
                  _FakeEither_3<_i11.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#updateMembership, [membership]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i15.Membership>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getExpiredMemberships(DateTime? currentDate) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMemberships, [currentDate]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getExpiredMemberships, [currentDate]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getExpiredReservations(
    DateTime? currentTime,
    Duration? reservationDuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredReservations, [
              currentTime,
              reservationDuration,
            ]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getExpiredReservations, [
                      currentTime,
                      reservationDuration,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> batchUpdateMembershipStatus(
    List<_i15.Membership>? memberships,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateMembershipStatus, [memberships]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#batchUpdateMembershipStatus, [memberships]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getExpiringMemberships({
    required String? libraryId,
    required DateTime? currentDate,
    required int? daysThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringMemberships, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
              #daysThreshold: daysThreshold,
            }),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getExpiringMemberships, [], {
                      #libraryId: libraryId,
                      #currentDate: currentDate,
                      #daysThreshold: daysThreshold,
                    }),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getUnregisteredMembershipsByPhone(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getUnregisteredMembershipsByPhone, [
              phoneNumber,
            ]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getUnregisteredMembershipsByPhone, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getMembershipsByPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByPhoneNumber, [phoneNumber]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByPhoneNumber, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>
  getPendingApprovalMemberships(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovalMemberships, [libraryId]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i15.Membership>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i15.Membership>>(
                    this,
                    Invocation.method(#getPendingApprovalMemberships, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i15.Membership>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> batchLinkMembershipsToUser({
    required String? phoneNumber,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchLinkMembershipsToUser, [], {
              #phoneNumber: phoneNumber,
              #userId: userId,
            }),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#batchLinkMembershipsToUser, [], {
                  #phoneNumber: phoneNumber,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> deleteMembership(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMembership, [membershipId]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#deleteMembership, [membershipId]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, Map<String, int>>>
  getActiveMembershipCountsByLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipCountsByLibrary, []),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, Map<String, int>>>.value(
                  _FakeEither_3<_i11.Failure, Map<String, int>>(
                    this,
                    Invocation.method(#getActiveMembershipCountsByLibrary, []),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, Map<String, int>>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i19.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User>> createUser(
    _i17.User? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, _i17.User>>.value(
              _FakeEither_3<_i11.Failure, _i17.User>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User>> getUserById(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, _i17.User>>.value(
              _FakeEither_3<_i11.Failure, _i17.User>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User?>> getUserByEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>.value(
                  _FakeEither_3<_i11.Failure, _i17.User?>(
                    this,
                    Invocation.method(#getUserByEmail, [email]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User?>> getUserByPhone(
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phone]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>.value(
                  _FakeEither_3<_i11.Failure, _i17.User?>(
                    this,
                    Invocation.method(#getUserByPhone, [phone]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User?>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, _i17.User>> updateUser(
    _i17.User? user,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, _i17.User>>.value(
              _FakeEither_3<_i11.Failure, _i17.User>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, _i17.User>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, Map<String, _i17.User>>> getUsersByIds(
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [userIds]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, Map<String, _i17.User>>
                >.value(
                  _FakeEither_3<_i11.Failure, Map<String, _i17.User>>(
                    this,
                    Invocation.method(#getUsersByIds, [userIds]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, Map<String, _i17.User>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, bool>> userExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [userId]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, bool>>.value(
              _FakeEither_3<_i11.Failure, bool>(
                this,
                Invocation.method(#userExists, [userId]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, bool>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i17.User>>> getUsersByRole(
    _i17.UserRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role]),
            returnValue:
                _i10.Future<_i5.Either<_i11.Failure, List<_i17.User>>>.value(
                  _FakeEither_3<_i11.Failure, List<_i17.User>>(
                    this,
                    Invocation.method(#getUsersByRole, [role]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i17.User>>>);

  @override
  _i10.Future<_i5.Either<_i11.Failure, void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i10.Future<_i5.Either<_i11.Failure, void>>.value(
              _FakeEither_3<_i11.Failure, void>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, void>>);
}

/// A class which mocks [GetStudentDocuments].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetStudentDocuments extends _i1.Mock
    implements _i20.GetStudentDocuments {
  MockGetStudentDocuments() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.StudentDocumentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeStudentDocumentRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.StudentDocumentRepository);

  @override
  _i10.Future<_i5.Either<_i11.Failure, List<_i21.StudentDocument>>> call(
    _i20.GetStudentDocumentsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i10.Future<
                  _i5.Either<_i11.Failure, List<_i21.StudentDocument>>
                >.value(
                  _FakeEither_3<_i11.Failure, List<_i21.StudentDocument>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i10.Future<_i5.Either<_i11.Failure, List<_i21.StudentDocument>>>);
}
