// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/presentation/owner/owner_library_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/core.dart' as _i9;
import 'package:pg_manager/domain/entities/library.dart' as _i10;
import 'package:pg_manager/domain/entities/library_stats.dart' as _i12;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i2;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i4;
import 'package:pg_manager/domain/repositories/seat_repository.dart' as _i6;
import 'package:pg_manager/domain/repositories/slot_repository.dart' as _i5;
import 'package:pg_manager/domain/usecases/create_library.dart' as _i13;
import 'package:pg_manager/domain/usecases/get_library_stats.dart' as _i11;
import 'package:pg_manager/domain/usecases/get_owner_library.dart' as _i7;
import 'package:pg_manager/domain/usecases/update_library.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLibraryRepository_0 extends _i1.SmartFake
    implements _i2.LibraryRepository {
  _FakeLibraryRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMembershipRepository_2 extends _i1.SmartFake
    implements _i4.MembershipRepository {
  _FakeMembershipRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSlotRepository_3 extends _i1.SmartFake
    implements _i5.SlotRepository {
  _FakeSlotRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeatRepository_4 extends _i1.SmartFake
    implements _i6.SeatRepository {
  _FakeSeatRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetOwnerLibrary].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOwnerLibrary extends _i1.Mock implements _i7.GetOwnerLibrary {
  MockGetOwnerLibrary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LibraryRepository get libraryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#libraryRepository),
            returnValue: _FakeLibraryRepository_0(
              this,
              Invocation.getter(#libraryRepository),
            ),
          )
          as _i2.LibraryRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, _i10.Library?>> call(
    _i7.GetOwnerLibraryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i8.Future<_i3.Either<_i9.Failure, _i10.Library?>>.value(
                  _FakeEither_1<_i9.Failure, _i10.Library?>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, _i10.Library?>>);
}

/// A class which mocks [GetLibraryStats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLibraryStats extends _i1.Mock implements _i11.GetLibraryStats {
  MockGetLibraryStats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_2(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i4.MembershipRepository);

  @override
  _i5.SlotRepository get slotRepository =>
      (super.noSuchMethod(
            Invocation.getter(#slotRepository),
            returnValue: _FakeSlotRepository_3(
              this,
              Invocation.getter(#slotRepository),
            ),
          )
          as _i5.SlotRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, _i12.LibraryStats>> call(
    _i11.GetLibraryStatsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i8.Future<_i3.Either<_i9.Failure, _i12.LibraryStats>>.value(
                  _FakeEither_1<_i9.Failure, _i12.LibraryStats>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, _i12.LibraryStats>>);
}

/// A class which mocks [CreateLibrary].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateLibrary extends _i1.Mock implements _i13.CreateLibrary {
  MockCreateLibrary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LibraryRepository get libraryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#libraryRepository),
            returnValue: _FakeLibraryRepository_0(
              this,
              Invocation.getter(#libraryRepository),
            ),
          )
          as _i2.LibraryRepository);

  @override
  _i6.SeatRepository get seatRepository =>
      (super.noSuchMethod(
            Invocation.getter(#seatRepository),
            returnValue: _FakeSeatRepository_4(
              this,
              Invocation.getter(#seatRepository),
            ),
          )
          as _i6.SeatRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, _i10.Library>> call(
    _i13.CreateLibraryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i8.Future<_i3.Either<_i9.Failure, _i10.Library>>.value(
                  _FakeEither_1<_i9.Failure, _i10.Library>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, _i10.Library>>);
}

/// A class which mocks [UpdateLibrary].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateLibrary extends _i1.Mock implements _i14.UpdateLibrary {
  MockUpdateLibrary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LibraryRepository get libraryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#libraryRepository),
            returnValue: _FakeLibraryRepository_0(
              this,
              Invocation.getter(#libraryRepository),
            ),
          )
          as _i2.LibraryRepository);

  @override
  _i6.SeatRepository get seatRepository =>
      (super.noSuchMethod(
            Invocation.getter(#seatRepository),
            returnValue: _FakeSeatRepository_4(
              this,
              Invocation.getter(#seatRepository),
            ),
          )
          as _i6.SeatRepository);

  @override
  _i8.Future<_i3.Either<_i9.Failure, _i10.Library>> call(
    _i14.UpdateLibraryParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i8.Future<_i3.Either<_i9.Failure, _i10.Library>>.value(
                  _FakeEither_1<_i9.Failure, _i10.Library>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i8.Future<_i3.Either<_i9.Failure, _i10.Library>>);
}
