// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/presentation/owner/cubit/occupied_seats_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/core/services/analytics_service.dart' as _i8;
import 'package:pg_manager/domain/core/core.dart' as _i12;
import 'package:pg_manager/domain/entities/membership.dart' as _i15;
import 'package:pg_manager/domain/repositories/invoice_repository.dart' as _i9;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i5;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i2;
import 'package:pg_manager/domain/repositories/seat_repository.dart' as _i6;
import 'package:pg_manager/domain/repositories/slot_repository.dart' as _i7;
import 'package:pg_manager/domain/repositories/user_repository.dart' as _i3;
import 'package:pg_manager/domain/usecases/cancel_membership.dart' as _i17;
import 'package:pg_manager/domain/usecases/deactivate_membership.dart' as _i16;
import 'package:pg_manager/domain/usecases/get_expired_seats.dart' as _i13;
import 'package:pg_manager/domain/usecases/get_occupied_seats.dart' as _i10;
import 'package:pg_manager/domain/usecases/reassign_seat.dart' as _i14;
import 'package:pg_manager/domain/usecases/update_membership.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMembershipRepository_0 extends _i1.SmartFake
    implements _i2.MembershipRepository {
  _FakeMembershipRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_1 extends _i1.SmartFake
    implements _i3.UserRepository {
  _FakeUserRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_2<L, R> extends _i1.SmartFake implements _i4.Either<L, R> {
  _FakeEither_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLibraryRepository_3 extends _i1.SmartFake
    implements _i5.LibraryRepository {
  _FakeLibraryRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeatRepository_4 extends _i1.SmartFake
    implements _i6.SeatRepository {
  _FakeSeatRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSlotRepository_5 extends _i1.SmartFake
    implements _i7.SlotRepository {
  _FakeSlotRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnalyticsService_6 extends _i1.SmartFake
    implements _i8.AnalyticsService {
  _FakeAnalyticsService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInvoiceRepository_7 extends _i1.SmartFake
    implements _i9.InvoiceRepository {
  _FakeInvoiceRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetOccupiedSeats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOccupiedSeats extends _i1.Mock implements _i10.GetOccupiedSeats {
  MockGetOccupiedSeats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i3.UserRepository get userRepository =>
      (super.noSuchMethod(
            Invocation.getter(#userRepository),
            returnValue: _FakeUserRepository_1(
              this,
              Invocation.getter(#userRepository),
            ),
          )
          as _i3.UserRepository);

  @override
  _i11.Future<_i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>> call(
    _i10.GetOccupiedSeatsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<
                  _i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>
                >.value(
                  _FakeEither_2<_i12.Failure, List<_i10.OccupiedSeatInfo>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<
            _i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>
          >);
}

/// A class which mocks [GetExpiredSeats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetExpiredSeats extends _i1.Mock implements _i13.GetExpiredSeats {
  MockGetExpiredSeats() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i3.UserRepository get userRepository =>
      (super.noSuchMethod(
            Invocation.getter(#userRepository),
            returnValue: _FakeUserRepository_1(
              this,
              Invocation.getter(#userRepository),
            ),
          )
          as _i3.UserRepository);

  @override
  _i11.Future<_i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>> call(
    _i13.GetExpiredSeatsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<
                  _i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>
                >.value(
                  _FakeEither_2<_i12.Failure, List<_i10.OccupiedSeatInfo>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<
            _i4.Either<_i12.Failure, List<_i10.OccupiedSeatInfo>>
          >);
}

/// A class which mocks [ReassignSeat].
///
/// See the documentation for Mockito's code generation for more information.
class MockReassignSeat extends _i1.Mock implements _i14.ReassignSeat {
  MockReassignSeat() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i5.LibraryRepository get libraryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#libraryRepository),
            returnValue: _FakeLibraryRepository_3(
              this,
              Invocation.getter(#libraryRepository),
            ),
          )
          as _i5.LibraryRepository);

  @override
  _i6.SeatRepository get seatRepository =>
      (super.noSuchMethod(
            Invocation.getter(#seatRepository),
            returnValue: _FakeSeatRepository_4(
              this,
              Invocation.getter(#seatRepository),
            ),
          )
          as _i6.SeatRepository);

  @override
  _i7.SlotRepository get slotRepository =>
      (super.noSuchMethod(
            Invocation.getter(#slotRepository),
            returnValue: _FakeSlotRepository_5(
              this,
              Invocation.getter(#slotRepository),
            ),
          )
          as _i7.SlotRepository);

  @override
  _i8.AnalyticsService get analyticsService =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsService),
            returnValue: _FakeAnalyticsService_6(
              this,
              Invocation.getter(#analyticsService),
            ),
          )
          as _i8.AnalyticsService);

  @override
  _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>> call(
    _i14.ReassignSeatParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>.value(
                  _FakeEither_2<_i12.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>);
}

/// A class which mocks [DeactivateMembership].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeactivateMembership extends _i1.Mock
    implements _i16.DeactivateMembership {
  MockDeactivateMembership() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>> call(
    _i16.DeactivateMembershipParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>.value(
                  _FakeEither_2<_i12.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>);
}

/// A class which mocks [CancelMembership].
///
/// See the documentation for Mockito's code generation for more information.
class MockCancelMembership extends _i1.Mock implements _i17.CancelMembership {
  MockCancelMembership() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>> call(
    _i17.CancelMembershipParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>.value(
                  _FakeEither_2<_i12.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>);
}

/// A class which mocks [UpdateMembership].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateMembership extends _i1.Mock implements _i18.UpdateMembership {
  MockUpdateMembership() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MembershipRepository get membershipRepository =>
      (super.noSuchMethod(
            Invocation.getter(#membershipRepository),
            returnValue: _FakeMembershipRepository_0(
              this,
              Invocation.getter(#membershipRepository),
            ),
          )
          as _i2.MembershipRepository);

  @override
  _i9.InvoiceRepository get invoiceRepository =>
      (super.noSuchMethod(
            Invocation.getter(#invoiceRepository),
            returnValue: _FakeInvoiceRepository_7(
              this,
              Invocation.getter(#invoiceRepository),
            ),
          )
          as _i9.InvoiceRepository);

  @override
  _i7.SlotRepository get slotRepository =>
      (super.noSuchMethod(
            Invocation.getter(#slotRepository),
            returnValue: _FakeSlotRepository_5(
              this,
              Invocation.getter(#slotRepository),
            ),
          )
          as _i7.SlotRepository);

  @override
  _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>> call(
    _i18.UpdateMembershipParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>.value(
                  _FakeEither_2<_i12.Failure, _i15.Membership>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i11.Future<_i4.Either<_i12.Failure, _i15.Membership>>);
}
