// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/presentation/auth/phone_auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/core/services/analytics_service.dart' as _i12;
import 'package:pg_manager/domain/core/core.dart' as _i6;
import 'package:pg_manager/domain/entities/user.dart' as _i8;
import 'package:pg_manager/domain/repositories/auth_repository.dart' as _i2;
import 'package:pg_manager/domain/usecases/check_auth_status.dart' as _i9;
import 'package:pg_manager/domain/usecases/delete_account.dart' as _i11;
import 'package:pg_manager/domain/usecases/send_otp.dart' as _i4;
import 'package:pg_manager/domain/usecases/sign_out.dart' as _i10;
import 'package:pg_manager/domain/usecases/verify_otp.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthRepository_0 extends _i1.SmartFake
    implements _i2.AuthRepository {
  _FakeAuthRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SendOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendOtp extends _i1.Mock implements _i4.SendOtp {
  MockSendOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> call(_i4.SendOtpParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [VerifyOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtp extends _i1.Mock implements _i7.VerifyOtp {
  MockVerifyOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User>> call(
    _i7.VerifyOtpParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User>>.value(
              _FakeEither_1<_i6.Failure, _i8.User>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User>>);
}

/// A class which mocks [CheckAuthStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthStatus extends _i1.Mock implements _i9.CheckAuthStatus {
  MockCheckAuthStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.AuthStatus>> call(
    _i9.CheckAuthStatusParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, _i9.AuthStatus>>.value(
                  _FakeEither_1<_i6.Failure, _i9.AuthStatus>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i9.AuthStatus>>);
}

/// A class which mocks [SignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOut extends _i1.Mock implements _i10.SignOut {
  MockSignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [DeleteAccount].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteAccount extends _i1.Mock implements _i11.DeleteAccount {
  MockDeleteAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_0(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i2.AuthRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i6.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i8.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i5.Stream<_i8.User?>.empty(),
          )
          as _i5.Stream<_i8.User?>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> sendOtp(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [phoneNumber]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#sendOtp, [phoneNumber]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User>> verifyOtp({
    required String? verificationId,
    required String? otp,
    required String? deviceId,
    required _i8.UserRole? role,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #verificationId: verificationId,
              #otp: otp,
              #deviceId: deviceId,
              #role: role,
              #name: name,
            }),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User>>.value(
              _FakeEither_1<_i6.Failure, _i8.User>(
                this,
                Invocation.method(#verifyOtp, [], {
                  #verificationId: verificationId,
                  #otp: otp,
                  #deviceId: deviceId,
                  #role: role,
                  #name: name,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>.value(
              _FakeEither_1<_i6.Failure, _i8.User?>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User?>> getUserByDeviceId(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByDeviceId, [deviceId]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>.value(
              _FakeEither_1<_i6.Failure, _i8.User?>(
                this,
                Invocation.method(#getUserByDeviceId, [deviceId]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User?>> getUserByPhone(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phoneNumber]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>.value(
              _FakeEither_1<_i6.Failure, _i8.User?>(
                this,
                Invocation.method(#getUserByPhone, [phoneNumber]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User?>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
              _FakeEither_1<_i6.Failure, String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, String>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User>> updateUserProfile({
    required String? userId,
    required String? name,
    String? avatarUrl,
    String? examPreparingFor,
    bool? isAccessCardIssued,
    String? address,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #userId: userId,
              #name: name,
              #avatarUrl: avatarUrl,
              #examPreparingFor: examPreparingFor,
              #isAccessCardIssued: isAccessCardIssued,
              #address: address,
              #gender: gender,
            }),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User>>.value(
              _FakeEither_1<_i6.Failure, _i8.User>(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #userId: userId,
                  #name: name,
                  #avatarUrl: avatarUrl,
                  #examPreparingFor: examPreparingFor,
                  #isAccessCardIssued: isAccessCardIssued,
                  #address: address,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i8.User>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i12.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> trackEvent(
    String? eventName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #trackEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setUserContext({
    required String? userId,
    required String? userRole,
    String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userId: userId,
              #userRole: userRole,
              #libraryId: libraryId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearUserContext() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserContext, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackMembershipCreated({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipCreated, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackMembershipRenewed({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipRenewed, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackAttendanceMarked({
    required String? studentId,
    required String? attendanceType,
    required String? sessionType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttendanceMarked, [], {
              #studentId: studentId,
              #attendanceType: attendanceType,
              #sessionType: sessionType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackBulkAttendanceMarked({
    required int? studentCount,
    required String? attendanceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkAttendanceMarked, [], {
              #studentCount: studentCount,
              #attendanceType: attendanceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackSeatAssigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatAssigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackSeatUnassigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatUnassigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackInvoiceGenerated({
    required String? invoiceId,
    required String? invoiceType,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceGenerated, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackInvoiceDownloaded({
    required String? invoiceId,
    required String? invoiceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceDownloaded, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackInvoiceShared({
    required String? invoiceId,
    required String? invoiceType,
    required String? shareMethod,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceShared, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #shareMethod: shareMethod,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackPaymentFailed({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? failureReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentFailed, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #failureReason: failureReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackPaymentRefunded({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? reason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentRefunded, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #reason: reason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackStudentUtilityUsed({
    required String? utilityName,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackStudentUtilityUsed, [], {
              #utilityName: utilityName,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackBulkImportUsed({
    required String? importType,
    required int? recordCount,
    required bool? success,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkImportUsed, [], {
              #importType: importType,
              #recordCount: recordCount,
              #success: success,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackSubscriptionPurchased({
    required String? subscriptionPlan,
    required double? amount,
    required String? duration,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionPurchased, [], {
              #subscriptionPlan: subscriptionPlan,
              #amount: amount,
              #duration: duration,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> trackSubscriptionCancelled({
    required String? subscriptionPlan,
    required String? cancellationReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionCancelled, [], {
              #subscriptionPlan: subscriptionPlan,
              #cancellationReason: cancellationReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
