// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/check_auth_status_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/failure.dart' as _i6;
import 'package:pg_manager/domain/entities/user.dart' as _i5;
import 'package:pg_manager/domain/repositories/auth_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.User?>.empty(),
          )
          as _i4.Stream<_i5.User?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> sendOtp(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [phoneNumber]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#sendOtp, [phoneNumber]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> verifyOtp({
    required String? verificationId,
    required String? otp,
    required String? deviceId,
    required _i5.UserRole? role,
    String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [], {
              #verificationId: verificationId,
              #otp: otp,
              #deviceId: deviceId,
              #role: role,
              #name: name,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
              _FakeEither_0<_i6.Failure, _i5.User>(
                this,
                Invocation.method(#verifyOtp, [], {
                  #verificationId: verificationId,
                  #otp: otp,
                  #deviceId: deviceId,
                  #role: role,
                  #name: name,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
              _FakeEither_0<_i6.Failure, _i5.User?>(
                this,
                Invocation.method(#getCurrentUser, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#deleteAccount, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User?>> getUserByDeviceId(
    String? deviceId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByDeviceId, [deviceId]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
              _FakeEither_0<_i6.Failure, _i5.User?>(
                this,
                Invocation.method(#getUserByDeviceId, [deviceId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User?>> getUserByPhone(
    String? phoneNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phoneNumber]),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>.value(
              _FakeEither_0<_i6.Failure, _i5.User?>(
                this,
                Invocation.method(#getUserByPhone, [phoneNumber]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, String>> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, String>>.value(
              _FakeEither_0<_i6.Failure, String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.User>> updateUserProfile({
    required String? userId,
    required String? name,
    String? avatarUrl,
    String? examPreparingFor,
    bool? isAccessCardIssued,
    String? address,
    String? gender,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [], {
              #userId: userId,
              #name: name,
              #avatarUrl: avatarUrl,
              #examPreparingFor: examPreparingFor,
              #isAccessCardIssued: isAccessCardIssued,
              #address: address,
              #gender: gender,
            }),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, _i5.User>>.value(
              _FakeEither_0<_i6.Failure, _i5.User>(
                this,
                Invocation.method(#updateUserProfile, [], {
                  #userId: userId,
                  #name: name,
                  #avatarUrl: avatarUrl,
                  #examPreparingFor: examPreparingFor,
                  #isAccessCardIssued: isAccessCardIssued,
                  #address: address,
                  #gender: gender,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.User>>);
}
