// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/delete_library_photo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/library.dart' as _i6;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i3;
import 'package:pg_manager/domain/services/storage_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LibraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryRepository extends _i1.Mock implements _i3.LibraryRepository {
  MockLibraryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library>> createLibrary(
    _i6.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>.value(
              _FakeEither_0<_i5.Failure, _i6.Library>(
                this,
                Invocation.method(#createLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library>> updateLibrary(
    _i6.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>.value(
              _FakeEither_0<_i5.Failure, _i6.Library>(
                this,
                Invocation.method(#updateLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>> getLibraryById(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryById, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Library?>(
                    this,
                    Invocation.method(#getLibraryById, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>> getLibraryByOwnerId(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryByOwnerId, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Library?>(
                    this,
                    Invocation.method(#getLibraryByOwnerId, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> ownerHasLibrary(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#ownerHasLibrary, [ownerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#ownerHasLibrary, [ownerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>
  getAllCompletedLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCompletedLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Library>>(
                    this,
                    Invocation.method(#getAllCompletedLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>> getAllLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Library>>(
                    this,
                    Invocation.method(#getAllLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i7.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> uploadImage({
    required _i8.File? file,
    required String? path,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [], {#file: file, #path: path}),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#uploadImage, [], {#file: file, #path: path}),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> deleteImage(String? downloadUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [downloadUrl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> deleteImages(List<String>? downloadUrls) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImages, [downloadUrls]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
