// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/get_all_libraries_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/library.dart' as _i6;
import 'package:pg_manager/domain/entities/user.dart' as _i8;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i3;
import 'package:pg_manager/domain/repositories/user_repository.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LibraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryRepository extends _i1.Mock implements _i3.LibraryRepository {
  MockLibraryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library>> createLibrary(
    _i6.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>.value(
              _FakeEither_0<_i5.Failure, _i6.Library>(
                this,
                Invocation.method(#createLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library>> updateLibrary(
    _i6.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>.value(
              _FakeEither_0<_i5.Failure, _i6.Library>(
                this,
                Invocation.method(#updateLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>> getLibraryById(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryById, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Library?>(
                    this,
                    Invocation.method(#getLibraryById, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>> getLibraryByOwnerId(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryByOwnerId, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Library?>(
                    this,
                    Invocation.method(#getLibraryByOwnerId, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> ownerHasLibrary(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#ownerHasLibrary, [ownerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#ownerHasLibrary, [ownerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>
  getAllCompletedLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCompletedLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Library>>(
                    this,
                    Invocation.method(#getAllCompletedLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>> getAllLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Library>>(
                    this,
                    Invocation.method(#getAllLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Library>>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i7.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User>> createUser(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User>>.value(
              _FakeEither_0<_i5.Failure, _i8.User>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User>> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User>>.value(
              _FakeEither_0<_i5.Failure, _i8.User>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User?>> getUserByEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>.value(
              _FakeEither_0<_i5.Failure, _i8.User?>(
                this,
                Invocation.method(#getUserByEmail, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User?>> getUserByPhone(
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phone]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>.value(
              _FakeEither_0<_i5.Failure, _i8.User?>(
                this,
                Invocation.method(#getUserByPhone, [phone]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.User>> updateUser(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.User>>.value(
              _FakeEither_0<_i5.Failure, _i8.User>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, _i8.User>>> getUsersByIds(
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [userIds]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, Map<String, _i8.User>>
                >.value(
                  _FakeEither_0<_i5.Failure, Map<String, _i8.User>>(
                    this,
                    Invocation.method(#getUsersByIds, [userIds]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, _i8.User>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> userExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#userExists, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.User>>> getUsersByRole(
    _i8.UserRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.User>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.User>>(
                    this,
                    Invocation.method(#getUsersByRole, [role]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.User>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
