// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/handle_payment_failure_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/core/services/analytics_service.dart' as _i10;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/membership.dart' as _i6;
import 'package:pg_manager/domain/entities/payment.dart' as _i9;
import 'package:pg_manager/domain/entities/slot.dart' as _i7;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i3;
import 'package:pg_manager/domain/repositories/payment_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MembershipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembershipRepository extends _i1.Mock
    implements _i3.MembershipRepository {
  MockMembershipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> createMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#createMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> getMembershipById(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipById, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#getMembershipById, [membershipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserLibraryAndSlot({
    required String? userId,
    required String? libraryId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserLibraryAndSlot, [], {
              #userId: userId,
              #libraryId: libraryId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserLibraryAndSlot,
                      [],
                      {#userId: userId, #libraryId: libraryId, #slot: slot},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveMembershipsByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByUserId, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByUserId, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsForLibrary, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getActiveMembershipsForLibrary, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveAndReservedMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAndReservedMembershipsForLibrary, [
              libraryId,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveAndReservedMembershipsForLibrary,
                      [libraryId],
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMembershipsWithSeatsForLibrary({
    required String? libraryId,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMembershipsWithSeatsForLibrary, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getExpiredMembershipsWithSeatsForLibrary,
                      [],
                      {#libraryId: libraryId, #currentDate: currentDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isSeatSlotOccupied({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSeatSlotOccupied, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isSeatSlotOccupied, [], {
                  #libraryId: libraryId,
                  #seatId: seatId,
                  #slot: slot,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getMembershipBySeatAndSlot({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipBySeatAndSlot, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(#getMembershipBySeatAndSlot, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                      #slot: slot,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsBySeatId({
    required String? libraryId,
    required String? seatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsBySeatId, [], {
              #libraryId: libraryId,
              #seatId: seatId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsBySeatId, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> updateMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#updateMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMemberships(DateTime? currentDate) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMemberships, [currentDate]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredMemberships, [currentDate]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredReservations(
    DateTime? currentTime,
    Duration? reservationDuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredReservations, [
              currentTime,
              reservationDuration,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredReservations, [
                      currentTime,
                      reservationDuration,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchUpdateMembershipStatus(
    List<_i6.Membership>? memberships,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateMembershipStatus, [memberships]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchUpdateMembershipStatus, [memberships]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiringMemberships({
    required String? libraryId,
    required DateTime? currentDate,
    required int? daysThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringMemberships, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
              #daysThreshold: daysThreshold,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiringMemberships, [], {
                      #libraryId: libraryId,
                      #currentDate: currentDate,
                      #daysThreshold: daysThreshold,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getUnregisteredMembershipsByPhone(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getUnregisteredMembershipsByPhone, [
              phoneNumber,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getUnregisteredMembershipsByPhone, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByPhoneNumber, [phoneNumber]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByPhoneNumber, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getPendingApprovalMemberships(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovalMemberships, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getPendingApprovalMemberships, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchLinkMembershipsToUser({
    required String? phoneNumber,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchLinkMembershipsToUser, [], {
              #phoneNumber: phoneNumber,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchLinkMembershipsToUser, [], {
                  #phoneNumber: phoneNumber,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMembership(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMembership, [membershipId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMembership, [membershipId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>
  getActiveMembershipCountsByLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipCountsByLibrary, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, int>>(
                    this,
                    Invocation.method(#getActiveMembershipCountsByLibrary, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>);
}

/// A class which mocks [PaymentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaymentRepository extends _i1.Mock implements _i8.PaymentRepository {
  MockPaymentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>> createPayment(
    _i9.Payment? payment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPayment, [payment]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>.value(
              _FakeEither_0<_i5.Failure, _i9.Payment>(
                this,
                Invocation.method(#createPayment, [payment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>> getPaymentById(
    String? paymentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentById, [paymentId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>.value(
              _FakeEither_0<_i5.Failure, _i9.Payment>(
                this,
                Invocation.method(#getPaymentById, [paymentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>> getPaymentByMembershipId(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentByMembershipId, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>>.value(
                  _FakeEither_0<_i5.Failure, _i9.Payment?>(
                    this,
                    Invocation.method(#getPaymentByMembershipId, [
                      membershipId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>
  getPaymentsByMembershipId(String? membershipId) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByMembershipId, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getPaymentsByMembershipId, [
                      membershipId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>>
  getPendingPaymentByMembershipId(String? membershipId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingPaymentByMembershipId, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>>.value(
                  _FakeEither_0<_i5.Failure, _i9.Payment?>(
                    this,
                    Invocation.method(#getPendingPaymentByMembershipId, [
                      membershipId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Payment?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>> updatePayment(
    _i9.Payment? payment,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePayment, [payment]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>.value(
              _FakeEither_0<_i5.Failure, _i9.Payment>(
                this,
                Invocation.method(#updatePayment, [payment]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Payment>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>
  getExpiredPendingPayments(DateTime? currentTime) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredPendingPayments, [currentTime]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getExpiredPendingPayments, [
                      currentTime,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>> getPendingCashPayments(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCashPayments, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getPendingCashPayments, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>
  getPendingApprovalPayments(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovalPayments, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getPendingApprovalPayments, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>> getCompletedPayments({
    required String? libraryId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCompletedPayments, [], {
              #libraryId: libraryId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getCompletedPayments, [], {
                      #libraryId: libraryId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>> getPaymentsByLibraryId(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Payment>>(
                    this,
                    Invocation.method(#getPaymentsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Payment>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deletePayment(String? paymentId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePayment, [paymentId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deletePayment, [paymentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i10.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> trackEvent(
    String? eventName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #trackEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserContext({
    required String? userId,
    required String? userRole,
    String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userId: userId,
              #userRole: userRole,
              #libraryId: libraryId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserContext() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserContext, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipCreated({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipCreated, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipRenewed({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipRenewed, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackAttendanceMarked({
    required String? studentId,
    required String? attendanceType,
    required String? sessionType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttendanceMarked, [], {
              #studentId: studentId,
              #attendanceType: attendanceType,
              #sessionType: sessionType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkAttendanceMarked({
    required int? studentCount,
    required String? attendanceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkAttendanceMarked, [], {
              #studentCount: studentCount,
              #attendanceType: attendanceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatAssigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatAssigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatUnassigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatUnassigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceGenerated({
    required String? invoiceId,
    required String? invoiceType,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceGenerated, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceDownloaded({
    required String? invoiceId,
    required String? invoiceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceDownloaded, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceShared({
    required String? invoiceId,
    required String? invoiceType,
    required String? shareMethod,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceShared, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #shareMethod: shareMethod,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentFailed({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? failureReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentFailed, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #failureReason: failureReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentRefunded({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? reason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentRefunded, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #reason: reason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackStudentUtilityUsed({
    required String? utilityName,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackStudentUtilityUsed, [], {
              #utilityName: utilityName,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkImportUsed({
    required String? importType,
    required int? recordCount,
    required bool? success,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkImportUsed, [], {
              #importType: importType,
              #recordCount: recordCount,
              #success: success,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionPurchased({
    required String? subscriptionPlan,
    required double? amount,
    required String? duration,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionPurchased, [], {
              #subscriptionPlan: subscriptionPlan,
              #amount: amount,
              #duration: duration,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionCancelled({
    required String? subscriptionPlan,
    required String? cancellationReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionCancelled, [], {
              #subscriptionPlan: subscriptionPlan,
              #cancellationReason: cancellationReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
