// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/reassign_seat_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/core/services/analytics_service.dart' as _i14;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/custom_slot.dart' as _i13;
import 'package:pg_manager/domain/entities/library.dart' as _i9;
import 'package:pg_manager/domain/entities/membership.dart' as _i6;
import 'package:pg_manager/domain/entities/seat.dart' as _i11;
import 'package:pg_manager/domain/entities/slot.dart' as _i7;
import 'package:pg_manager/domain/repositories/library_repository.dart' as _i8;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i3;
import 'package:pg_manager/domain/repositories/seat_repository.dart' as _i10;
import 'package:pg_manager/domain/repositories/slot_repository.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MembershipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembershipRepository extends _i1.Mock
    implements _i3.MembershipRepository {
  MockMembershipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> createMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#createMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> getMembershipById(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipById, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#getMembershipById, [membershipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserLibraryAndSlot({
    required String? userId,
    required String? libraryId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserLibraryAndSlot, [], {
              #userId: userId,
              #libraryId: libraryId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserLibraryAndSlot,
                      [],
                      {#userId: userId, #libraryId: libraryId, #slot: slot},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveMembershipsByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByUserId, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByUserId, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsForLibrary, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getActiveMembershipsForLibrary, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveAndReservedMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAndReservedMembershipsForLibrary, [
              libraryId,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveAndReservedMembershipsForLibrary,
                      [libraryId],
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMembershipsWithSeatsForLibrary({
    required String? libraryId,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMembershipsWithSeatsForLibrary, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getExpiredMembershipsWithSeatsForLibrary,
                      [],
                      {#libraryId: libraryId, #currentDate: currentDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isSeatSlotOccupied({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSeatSlotOccupied, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isSeatSlotOccupied, [], {
                  #libraryId: libraryId,
                  #seatId: seatId,
                  #slot: slot,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getMembershipBySeatAndSlot({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipBySeatAndSlot, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(#getMembershipBySeatAndSlot, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                      #slot: slot,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsBySeatId({
    required String? libraryId,
    required String? seatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsBySeatId, [], {
              #libraryId: libraryId,
              #seatId: seatId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsBySeatId, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> updateMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#updateMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMemberships(DateTime? currentDate) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMemberships, [currentDate]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredMemberships, [currentDate]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredReservations(
    DateTime? currentTime,
    Duration? reservationDuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredReservations, [
              currentTime,
              reservationDuration,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredReservations, [
                      currentTime,
                      reservationDuration,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchUpdateMembershipStatus(
    List<_i6.Membership>? memberships,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateMembershipStatus, [memberships]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchUpdateMembershipStatus, [memberships]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiringMemberships({
    required String? libraryId,
    required DateTime? currentDate,
    required int? daysThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringMemberships, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
              #daysThreshold: daysThreshold,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiringMemberships, [], {
                      #libraryId: libraryId,
                      #currentDate: currentDate,
                      #daysThreshold: daysThreshold,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getUnregisteredMembershipsByPhone(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getUnregisteredMembershipsByPhone, [
              phoneNumber,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getUnregisteredMembershipsByPhone, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByPhoneNumber, [phoneNumber]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByPhoneNumber, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getPendingApprovalMemberships(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovalMemberships, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getPendingApprovalMemberships, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchLinkMembershipsToUser({
    required String? phoneNumber,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchLinkMembershipsToUser, [], {
              #phoneNumber: phoneNumber,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchLinkMembershipsToUser, [], {
                  #phoneNumber: phoneNumber,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMembership(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMembership, [membershipId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMembership, [membershipId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>
  getActiveMembershipCountsByLibrary() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipCountsByLibrary, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, int>>(
                    this,
                    Invocation.method(#getActiveMembershipCountsByLibrary, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, int>>>);
}

/// A class which mocks [LibraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryRepository extends _i1.Mock implements _i8.LibraryRepository {
  MockLibraryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Library>> createLibrary(
    _i9.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Library>>.value(
              _FakeEither_0<_i5.Failure, _i9.Library>(
                this,
                Invocation.method(#createLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Library>> updateLibrary(
    _i9.Library? library,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLibrary, [library]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.Library>>.value(
              _FakeEither_0<_i5.Failure, _i9.Library>(
                this,
                Invocation.method(#updateLibrary, [library]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Library>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>> getLibraryById(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryById, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i9.Library?>(
                    this,
                    Invocation.method(#getLibraryById, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>> getLibraryByOwnerId(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLibraryByOwnerId, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>>.value(
                  _FakeEither_0<_i5.Failure, _i9.Library?>(
                    this,
                    Invocation.method(#getLibraryByOwnerId, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.Library?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> ownerHasLibrary(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#ownerHasLibrary, [ownerId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#ownerHasLibrary, [ownerId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>>
  getAllCompletedLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCompletedLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Library>>(
                    this,
                    Invocation.method(#getAllCompletedLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>> getAllLibraries() =>
      (super.noSuchMethod(
            Invocation.method(#getAllLibraries, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.Library>>(
                    this,
                    Invocation.method(#getAllLibraries, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.Library>>>);
}

/// A class which mocks [SeatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeatRepository extends _i1.Mock implements _i10.SeatRepository {
  MockSeatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>> createSeats({
    required String? libraryId,
    required int? count,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSeats, [], {
              #libraryId: libraryId,
              #count: count,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i11.Seat>>(
                    this,
                    Invocation.method(#createSeats, [], {
                      #libraryId: libraryId,
                      #count: count,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>> getSeatById(String? seatId) =>
      (super.noSuchMethod(
            Invocation.method(#getSeatById, [seatId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>>.value(
              _FakeEither_0<_i5.Failure, _i11.Seat>(
                this,
                Invocation.method(#getSeatById, [seatId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>> getSeatsByLibraryId(
    String? libraryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeatsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i11.Seat>>(
                    this,
                    Invocation.method(#getSeatsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>
  getActiveSeatsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSeatsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i11.Seat>>(
                    this,
                    Invocation.method(#getActiveSeatsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i11.Seat>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>> updateSeat(_i11.Seat? seat) =>
      (super.noSuchMethod(
            Invocation.method(#updateSeat, [seat]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>>.value(
              _FakeEither_0<_i5.Failure, _i11.Seat>(
                this,
                Invocation.method(#updateSeat, [seat]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i11.Seat>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSeatsForLibrary(
    String? libraryId, {
    int? keepCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteSeatsForLibrary,
              [libraryId],
              {#keepCount: keepCount},
            ),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(
                  #deleteSeatsForLibrary,
                  [libraryId],
                  {#keepCount: keepCount},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [SlotRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlotRepository extends _i1.Mock implements _i12.SlotRepository {
  MockSlotRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>> createSlot(
    _i13.CustomSlot? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSlot, [slot]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>>.value(
                  _FakeEither_0<_i5.Failure, _i13.CustomSlot>(
                    this,
                    Invocation.method(#createSlot, [slot]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>> updateSlot(
    _i13.CustomSlot? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSlot, [slot]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>>.value(
                  _FakeEither_0<_i5.Failure, _i13.CustomSlot>(
                    this,
                    Invocation.method(#updateSlot, [slot]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSlot(
    String? libraryId,
    String? slotId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSlot, [libraryId, slotId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteSlot, [libraryId, slotId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot?>> getSlotById(
    String? libraryId,
    String? slotId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSlotById, [libraryId, slotId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot?>>.value(
                  _FakeEither_0<_i5.Failure, _i13.CustomSlot?>(
                    this,
                    Invocation.method(#getSlotById, [libraryId, slotId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i13.CustomSlot?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i13.CustomSlot>>>
  getSlotsByLibraryId(String? libraryId, {bool? activeOnly}) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSlotsByLibraryId,
              [libraryId],
              {#activeOnly: activeOnly},
            ),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i13.CustomSlot>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i13.CustomSlot>>(
                    this,
                    Invocation.method(
                      #getSlotsByLibraryId,
                      [libraryId],
                      {#activeOnly: activeOnly},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i13.CustomSlot>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i13.CustomSlot>>>
  getActiveSlotsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSlotsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i13.CustomSlot>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i13.CustomSlot>>(
                    this,
                    Invocation.method(#getActiveSlotsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i13.CustomSlot>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> hasOverlappingSlot(
    String? libraryId,
    _i13.CustomSlot? slot,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#hasOverlappingSlot, [libraryId, slot]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#hasOverlappingSlot, [libraryId, slot]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i14.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> trackEvent(
    String? eventName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #trackEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserContext({
    required String? userId,
    required String? userRole,
    String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userId: userId,
              #userRole: userRole,
              #libraryId: libraryId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserContext() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserContext, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipCreated({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipCreated, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipRenewed({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipRenewed, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackAttendanceMarked({
    required String? studentId,
    required String? attendanceType,
    required String? sessionType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttendanceMarked, [], {
              #studentId: studentId,
              #attendanceType: attendanceType,
              #sessionType: sessionType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkAttendanceMarked({
    required int? studentCount,
    required String? attendanceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkAttendanceMarked, [], {
              #studentCount: studentCount,
              #attendanceType: attendanceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatAssigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatAssigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatUnassigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatUnassigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceGenerated({
    required String? invoiceId,
    required String? invoiceType,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceGenerated, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceDownloaded({
    required String? invoiceId,
    required String? invoiceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceDownloaded, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceShared({
    required String? invoiceId,
    required String? invoiceType,
    required String? shareMethod,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceShared, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #shareMethod: shareMethod,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentFailed({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? failureReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentFailed, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #failureReason: failureReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentRefunded({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? reason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentRefunded, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #reason: reason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackStudentUtilityUsed({
    required String? utilityName,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackStudentUtilityUsed, [], {
              #utilityName: utilityName,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkImportUsed({
    required String? importType,
    required int? recordCount,
    required bool? success,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkImportUsed, [], {
              #importType: importType,
              #recordCount: recordCount,
              #success: success,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionPurchased({
    required String? subscriptionPlan,
    required double? amount,
    required String? duration,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionPurchased, [], {
              #subscriptionPlan: subscriptionPlan,
              #amount: amount,
              #duration: duration,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionCancelled({
    required String? subscriptionPlan,
    required String? cancellationReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionCancelled, [], {
              #subscriptionPlan: subscriptionPlan,
              #cancellationReason: cancellationReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
