// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/reject_subscription_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/core/services/analytics_service.dart' as _i9;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/coupon.dart' as _i8;
import 'package:pg_manager/domain/entities/owner_trial.dart' as _i7;
import 'package:pg_manager/domain/entities/subscription.dart' as _i6;
import 'package:pg_manager/domain/repositories/subscription_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionRepository extends _i1.Mock
    implements _i3.SubscriptionRepository {
  MockSubscriptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>> createSubscription(
    _i6.Subscription? subscription,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSubscription, [subscription]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Subscription>(
                    this,
                    Invocation.method(#createSubscription, [subscription]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>> updateSubscription(
    _i6.Subscription? subscription,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSubscription, [subscription]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Subscription>(
                    this,
                    Invocation.method(#updateSubscription, [subscription]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>> getActiveSubscription(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveSubscription, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Subscription?>(
                    this,
                    Invocation.method(#getActiveSubscription, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>> getSubscriptionById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Subscription>(
                    this,
                    Invocation.method(#getSubscriptionById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>
  getSubscriptionHistory(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionHistory, [ownerId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Subscription>>(
                    this,
                    Invocation.method(#getSubscriptionHistory, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>
  getPendingVerificationSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingVerificationSubscriptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Subscription>>(
                    this,
                    Invocation.method(#getPendingVerificationSubscriptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>>
  getLatestPendingSubscription(String? ownerId) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestPendingSubscription, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Subscription?>(
                    this,
                    Invocation.method(#getLatestPendingSubscription, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Subscription?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>
  getAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubscriptions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.Subscription>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Subscription>>(
                    this,
                    Invocation.method(#getAllSubscriptions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Subscription>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteSubscription(
    String? subscriptionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSubscription, [subscriptionId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteSubscription, [subscriptionId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>> getOrCreateTrial(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateTrial, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>>.value(
                  _FakeEither_0<_i5.Failure, _i7.OwnerTrial>(
                    this,
                    Invocation.method(#getOrCreateTrial, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial?>> getTrial(
    String? ownerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTrial, [ownerId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial?>>.value(
                  _FakeEither_0<_i5.Failure, _i7.OwnerTrial?>(
                    this,
                    Invocation.method(#getTrial, [ownerId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>> updateTrial(
    _i7.OwnerTrial? trial,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrial, [trial]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>>.value(
                  _FakeEither_0<_i5.Failure, _i7.OwnerTrial>(
                    this,
                    Invocation.method(#updateTrial, [trial]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.OwnerTrial>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon?>> getCouponByCode(
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCouponByCode, [code]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon?>>.value(
              _FakeEither_0<_i5.Failure, _i8.Coupon?>(
                this,
                Invocation.method(#getCouponByCode, [code]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>> createCoupon(
    _i8.Coupon? coupon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCoupon, [coupon]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>>.value(
              _FakeEither_0<_i5.Failure, _i8.Coupon>(
                this,
                Invocation.method(#createCoupon, [coupon]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>> updateCoupon(
    _i8.Coupon? coupon,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCoupon, [coupon]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>>.value(
              _FakeEither_0<_i5.Failure, _i8.Coupon>(
                this,
                Invocation.method(#updateCoupon, [coupon]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.Coupon>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.Coupon>>> getAllCoupons() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCoupons, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i8.Coupon>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i8.Coupon>>(
                    this,
                    Invocation.method(#getAllCoupons, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.Coupon>>>);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i9.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> trackEvent(
    String? eventName, {
    Map<String, dynamic>? parameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #trackEvent,
              [eventName],
              {#parameters: parameters},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserContext({
    required String? userId,
    required String? userRole,
    String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setUserContext, [], {
              #userId: userId,
              #userRole: userRole,
              #libraryId: libraryId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearUserContext() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserContext, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipCreated({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipCreated, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackMembershipRenewed({
    required String? membershipId,
    required String? planType,
    required String? duration,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackMembershipRenewed, [], {
              #membershipId: membershipId,
              #planType: planType,
              #duration: duration,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackAttendanceMarked({
    required String? studentId,
    required String? attendanceType,
    required String? sessionType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackAttendanceMarked, [], {
              #studentId: studentId,
              #attendanceType: attendanceType,
              #sessionType: sessionType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkAttendanceMarked({
    required int? studentCount,
    required String? attendanceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkAttendanceMarked, [], {
              #studentCount: studentCount,
              #attendanceType: attendanceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatAssigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatAssigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSeatUnassigned({
    required String? seatNumber,
    required String? studentId,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSeatUnassigned, [], {
              #seatNumber: seatNumber,
              #studentId: studentId,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceGenerated({
    required String? invoiceId,
    required String? invoiceType,
    required double? amount,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceGenerated, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #amount: amount,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceDownloaded({
    required String? invoiceId,
    required String? invoiceType,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceDownloaded, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackInvoiceShared({
    required String? invoiceId,
    required String? invoiceType,
    required String? shareMethod,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackInvoiceShared, [], {
              #invoiceId: invoiceId,
              #invoiceType: invoiceType,
              #shareMethod: shareMethod,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentFailed({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? failureReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentFailed, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #failureReason: failureReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackPaymentRefunded({
    required String? paymentId,
    required String? paymentMethod,
    required double? amount,
    required String? reason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackPaymentRefunded, [], {
              #paymentId: paymentId,
              #paymentMethod: paymentMethod,
              #amount: amount,
              #reason: reason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackStudentUtilityUsed({
    required String? utilityName,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackStudentUtilityUsed, [], {
              #utilityName: utilityName,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackBulkImportUsed({
    required String? importType,
    required int? recordCount,
    required bool? success,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackBulkImportUsed, [], {
              #importType: importType,
              #recordCount: recordCount,
              #success: success,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionPurchased({
    required String? subscriptionPlan,
    required double? amount,
    required String? duration,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionPurchased, [], {
              #subscriptionPlan: subscriptionPlan,
              #amount: amount,
              #duration: duration,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> trackSubscriptionCancelled({
    required String? subscriptionPlan,
    required String? cancellationReason,
    Map<String, dynamic>? additionalParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#trackSubscriptionCancelled, [], {
              #subscriptionPlan: subscriptionPlan,
              #cancellationReason: cancellationReason,
              #additionalParams: additionalParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
