// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/reserve_seat_for_student_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/membership.dart' as _i6;
import 'package:pg_manager/domain/entities/slot.dart' as _i7;
import 'package:pg_manager/domain/entities/user.dart' as _i9;
import 'package:pg_manager/domain/repositories/membership_repository.dart'
    as _i3;
import 'package:pg_manager/domain/repositories/user_repository.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MembershipRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembershipRepository extends _i1.Mock
    implements _i3.MembershipRepository {
  MockMembershipRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> createMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#createMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> getMembershipById(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipById, [membershipId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#getMembershipById, [membershipId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getActiveMembershipByUserLibraryAndSlot({
    required String? userId,
    required String? libraryId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipByUserLibraryAndSlot, [], {
              #userId: userId,
              #libraryId: libraryId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(
                      #getActiveMembershipByUserLibraryAndSlot,
                      [],
                      {#userId: userId, #libraryId: libraryId, #slot: slot},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsByUserAndLibrary({
    required String? userId,
    required String? libraryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsByUserAndLibrary, [], {
              #userId: userId,
              #libraryId: libraryId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveMembershipsByUserAndLibrary,
                      [],
                      {#userId: userId, #libraryId: libraryId},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByUserId, [userId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByUserId, [userId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByLibraryId(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByLibraryId, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByLibraryId, [libraryId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveMembershipsForLibrary, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getActiveMembershipsForLibrary, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getActiveAndReservedMembershipsForLibrary(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveAndReservedMembershipsForLibrary, [
              libraryId,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getActiveAndReservedMembershipsForLibrary,
                      [libraryId],
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMembershipsWithSeatsForLibrary({
    required String? libraryId,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMembershipsWithSeatsForLibrary, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(
                      #getExpiredMembershipsWithSeatsForLibrary,
                      [],
                      {#libraryId: libraryId, #currentDate: currentDate},
                    ),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isSeatSlotOccupied({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#isSeatSlotOccupied, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#isSeatSlotOccupied, [], {
                  #libraryId: libraryId,
                  #seatId: seatId,
                  #slot: slot,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>
  getMembershipBySeatAndSlot({
    required String? libraryId,
    required String? seatId,
    required _i7.Slot? slot,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipBySeatAndSlot, [], {
              #libraryId: libraryId,
              #seatId: seatId,
              #slot: slot,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership?>(
                    this,
                    Invocation.method(#getMembershipBySeatAndSlot, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                      #slot: slot,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsBySeatId({
    required String? libraryId,
    required String? seatId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsBySeatId, [], {
              #libraryId: libraryId,
              #seatId: seatId,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsBySeatId, [], {
                      #libraryId: libraryId,
                      #seatId: seatId,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>> updateMembership(
    _i6.Membership? membership,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMembership, [membership]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Membership>(
                    this,
                    Invocation.method(#updateMembership, [membership]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Membership>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredMemberships(DateTime? currentDate) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredMemberships, [currentDate]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredMemberships, [currentDate]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiredReservations(
    DateTime? currentTime,
    Duration? reservationDuration,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiredReservations, [
              currentTime,
              reservationDuration,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiredReservations, [
                      currentTime,
                      reservationDuration,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchUpdateMembershipStatus(
    List<_i6.Membership>? memberships,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batchUpdateMembershipStatus, [memberships]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchUpdateMembershipStatus, [memberships]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getExpiringMemberships({
    required String? libraryId,
    required DateTime? currentDate,
    required int? daysThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getExpiringMemberships, [], {
              #libraryId: libraryId,
              #currentDate: currentDate,
              #daysThreshold: daysThreshold,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getExpiringMemberships, [], {
                      #libraryId: libraryId,
                      #currentDate: currentDate,
                      #daysThreshold: daysThreshold,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getUnregisteredMembershipsByPhone(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getUnregisteredMembershipsByPhone, [
              phoneNumber,
            ]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getUnregisteredMembershipsByPhone, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getMembershipsByPhoneNumber(String? phoneNumber) =>
      (super.noSuchMethod(
            Invocation.method(#getMembershipsByPhoneNumber, [phoneNumber]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getMembershipsByPhoneNumber, [
                      phoneNumber,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>
  getPendingApprovalMemberships(String? libraryId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingApprovalMemberships, [libraryId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Membership>>(
                    this,
                    Invocation.method(#getPendingApprovalMemberships, [
                      libraryId,
                    ]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Membership>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchLinkMembershipsToUser({
    required String? phoneNumber,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchLinkMembershipsToUser, [], {
              #phoneNumber: phoneNumber,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchLinkMembershipsToUser, [], {
                  #phoneNumber: phoneNumber,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteMembership(
    String? membershipId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMembership, [membershipId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteMembership, [membershipId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i8.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.User>> createUser(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.User>>.value(
              _FakeEither_0<_i5.Failure, _i9.User>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.User>> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.User>>.value(
              _FakeEither_0<_i5.Failure, _i9.User>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.User?>> getUserByEmail(
    String? email,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByEmail, [email]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.User?>>.value(
              _FakeEither_0<_i5.Failure, _i9.User?>(
                this,
                Invocation.method(#getUserByEmail, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.User?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.User?>> getUserByPhone(
    String? phone,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserByPhone, [phone]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.User?>>.value(
              _FakeEither_0<_i5.Failure, _i9.User?>(
                this,
                Invocation.method(#getUserByPhone, [phone]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.User?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.User>> updateUser(_i9.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i9.User>>.value(
              _FakeEither_0<_i5.Failure, _i9.User>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.User>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, _i9.User>>> getUsersByIds(
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByIds, [userIds]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, Map<String, _i9.User>>
                >.value(
                  _FakeEither_0<_i5.Failure, Map<String, _i9.User>>(
                    this,
                    Invocation.method(#getUsersByIds, [userIds]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, _i9.User>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> userExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
              _FakeEither_0<_i5.Failure, bool>(
                this,
                Invocation.method(#userExists, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i9.User>>> getUsersByRole(
    _i9.UserRole? role,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i9.User>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i9.User>>(
                    this,
                    Invocation.method(#getUsersByRole, [role]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i9.User>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
