// Mocks generated by Mockito 5.4.6 from annotations
// in pg_manager/test/domain/usecases/upload_student_document_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pg_manager/domain/core/failure.dart' as _i5;
import 'package:pg_manager/domain/entities/student_document.dart' as _i6;
import 'package:pg_manager/domain/repositories/student_document_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StudentDocumentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStudentDocumentRepository extends _i1.Mock
    implements _i3.StudentDocumentRepository {
  MockStudentDocumentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>> uploadDocument({
    required String? studentId,
    required String? filePath,
    required String? fileName,
    required _i6.StudentDocumentType? fileType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadDocument, [], {
              #studentId: studentId,
              #filePath: filePath,
              #fileName: fileName,
              #fileType: fileType,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>.value(
                  _FakeEither_0<_i5.Failure, _i6.StudentDocument>(
                    this,
                    Invocation.method(#uploadDocument, [], {
                      #studentId: studentId,
                      #filePath: filePath,
                      #fileName: fileName,
                      #fileType: fileType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.StudentDocument>>>
  getStudentDocuments(String? studentId) =>
      (super.noSuchMethod(
            Invocation.method(#getStudentDocuments, [studentId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.StudentDocument>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.StudentDocument>>(
                    this,
                    Invocation.method(#getStudentDocuments, [studentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.StudentDocument>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> deleteDocument(
    String? documentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDocument, [documentId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#deleteDocument, [documentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>> approveDocument({
    required String? documentId,
    required String? approvedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#approveDocument, [], {
              #documentId: documentId,
              #approvedBy: approvedBy,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>.value(
                  _FakeEither_0<_i5.Failure, _i6.StudentDocument>(
                    this,
                    Invocation.method(#approveDocument, [], {
                      #documentId: documentId,
                      #approvedBy: approvedBy,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>> rejectDocument({
    required String? documentId,
    required String? rejectedBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectDocument, [], {
              #documentId: documentId,
              #rejectedBy: rejectedBy,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>.value(
                  _FakeEither_0<_i5.Failure, _i6.StudentDocument>(
                    this,
                    Invocation.method(#rejectDocument, [], {
                      #documentId: documentId,
                      #rejectedBy: rejectedBy,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.StudentDocument>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> batchLinkDocumentsToUser({
    required String? phoneNumber,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#batchLinkDocumentsToUser, [], {
              #phoneNumber: phoneNumber,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#batchLinkDocumentsToUser, [], {
                  #phoneNumber: phoneNumber,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
